MAX_LENGTH = 256
MAX_LENGTH_EMAIL = 254
MAX_LENGTH_ROLE = 150
VALIDATE_DATE_ERROR = 'Год выпуска не может быть больше {year}'
USERNAME_SEARCH_REGEX = r'^[\w.@+-]+\Z'
NOT_ALLOWED_USERNAMES = ('me', 'admin')
RESPONSE_EMAIL = 'noreply@yamdb.fake'
MIN_REVIEW = 1
MAX_REVIEW = 10
